import type { Surah } from "./types";

export const BENGALI_SURAHS: Record<number, { name: string; translation: string }> = {
  1: { name: "আল-ফাতিহা", translation: "সূচনা" },
  2: { name: "আল-বাকারা", translation: "গাভী" },
  3: { name: "আলে ইমরান", translation: "ইমরানের পরিবার" },
  4: { name: "আন-নিসা", translation: "নারী" },
  5: { name: "আল-মায়িদাহ", translation: "খাদ্য পরিবেশিত টেবিল" },
  6: { name: "আল-আন'আম", translation: "গৃহপালিত পশু" },
  7: { name: "আল-আ'রাফ", translation: "উঁচু স্থানসমূহ" },
  8: { name: "আল-আনফাল", translation: "যুদ্ধলব্ধ সম্পদ" },
  9: { name: "আত-তাওবাহ", translation: "অনুশোচনা" },
  10: { name: "ইউনুস", translation: "নবী ইউনুস" },
  11: { name: "হুদ", translation: "নবী হুদ" },
  12: { name: "ইউসুফ", translation: "নবী ইউসুফ" },
  13: { name: "আর-রাদ", translation: "বজ্রপাত" },
  14: { name: "ইব্রাহীম", translation: "নবী ইব্রাহীম" },
  15: { name: "আল-হিজর", translation: "পাথুরে পাহাড়" },
  16: { name: "আন-নাহল", translation: "মৌমাছি" },
  17: { name: "আল-ইসরা", translation: "রাত্রিকালীন ভ্রমণ" },
  18: { name: "আল-কাহফ", translation: "গুহা" },
  19: { name: "মারইয়াম", translation: "মারইয়াম (আ.)" },
  20: { name: "ত্বোয়া-হা", translation: "ত্বোয়া-হা" },
  21: { name: "আল-আম্বিয়া", translation: "নবীগণ" },
  22: { name: "আল-হাজ্জ", translation: "হজ্জ" },
  23: { name: "আল-মু'মিনুন", translation: "বিশ্বাসীগণ" },
  24: { name: "আন-নূর", translation: "জ্যোতি" },
  25: { name: "আল-ফুরকান", translation: "সত্য-মিথ্যার পার্থক্যকারী" },
  26: { name: "আশ-শু'আরা", translation: "কবিগণ" },
  27: { name: "আন-নামল", translation: "পিঁপড়া" },
  28: { name: "আল-কাসাস", translation: "কাহিনী" },
  29: { name: "আল-আনকাবুত", translation: "মাকড়সা" },
  30: { name: "আর-রূম", translation: "রোমান জাতি" },
  31: { name: "লুকমান", translation: "লুকমান হাকিম" },
  32: { name: "আস-সাজদাহ", translation: "সিজদা" },
  33: { name: "আল-আহযাব", translation: "মিত্রবাহিনী" },
  34: { name: "সাবা", translation: "সাবা জাতি" },
  35: { name: "ফাতির", translation: "সৃষ্টিকর্তা" },
  36: { name: "ইয়াসীন", translation: "ইয়াসীন" },
  37: { name: "আস-সাফফাত", translation: "সারিবদ্ধ দলসমূহ" },
  38: { name: "সোয়াদ", translation: "সোয়াদ" },
  39: { name: "আজ-জুমার", translation: "দলসমূহ" },
  40: { name: "গাফির", translation: "ক্ষমাশীল" },
  41: { name: "ফুসসিলাত", translation: "সুস্পষ্ট বিবরণ" },
  42: { name: "আশ-শূরা", translation: "পরামর্শ" },
  43: { name: "আজ-জুখরুফ", translation: "স্বর্ণালঙ্কার" },
  44: { name: "আদ-দুখান", translation: "ধোঁয়া" },
  45: { name: "আল-জাসিয়াহ", translation: "নতজানু" },
  46: { name: "আল-আহকাফ", translation: "বালির পাহাড়" },
  47: { name: "মুহাম্মদ", translation: "নবী মুহাম্মদ (সা.)" },
  48: { name: "আল-ফাতহ", translation: "বিজয়" },
  49: { name: "আল-হুজুরাত", translation: "বাসগৃহসমূহ" },
  50: { name: "ক্বাফ", translation: "ক্বাফ" },
  51: { name: "আজ-যারিয়াত", translation: "বিক্ষিপ্তকারী বাতাস" },
  52: { name: "আত-তূর", translation: "তূর পর্বত" },
  53: { name: "আন-নাজম", translation: "নক্ষত্র" },
  54: { name: "আল-কামার", translation: "চাঁদ" },
  55: { name: "আর-রাহমান", translation: "পরম দয়ালু" },
  56: { name: "আল-ওয়াকিয়াহ", translation: "অনিবার্য ঘটনা" },
  57: { name: "আল-হাদীদ", translation: "লোহা" },
  58: { name: "আল-মুজাদালাহ", translation: "বিতর্ককারিণী নারী" },
  59: { name: "আল-হাশর", translation: "সমাবেশ" },
  60: { name: "আল-মুমতাহানাহ", translation: "পরীক্ষিত নারী" },
  61: { name: "আস-সাফ", translation: "সারিবদ্ধ সৈন্য" },
  62: { name: "আল-জুমু'আহ", translation: "শুক্রবার" },
  63: { name: "আল-মুনাফিকুন", translation: "কপট বিশ্বাসীগণ" },
  64: { name: "আত-তাগাবুন", translation: "লাভ-ক্ষতি" },
  65: { name: "আত-তালাক", translation: "বিবাহবিচ্ছেদ" },
  66: { name: "আত-তাহরীম", translation: "নিষিদ্ধকরণ" },
  67: { name: "আল-মুলক", translation: "সার্বভৌম কর্তৃত্ব" },
  68: { name: "আল-কলম", translation: "কলম" },
  69: { name: "আল-হাক্কাহ", translation: "অনিবার্য সত্য" },
  70: { name: "আল-মা'আরিজ", translation: "উন্নয়নের সোপান" },
  71: { name: "নূহ", translation: "নবী নূহ" },
  72: { name: "আল-জিন", translation: "জিন সম্প্রদায়" },
  73: { name: "আল-মুযযাম্মিল", translation: "বস্ত্রাবৃত" },
  74: { name: "আল-মুদ্দাচ্ছির", translation: "চাদরাবৃত" },
  75: { name: "আল-কিয়ামাহ", translation: "পুনরুত্থান" },
  76: { name: "আল-ইনসান", translation: "মানবজাতি" },
  77: { name: "আল-মুরসালাত", translation: "প্রেরিত বাতাস" },
  78: { name: "আন-নাবা", translation: "মহাসংবাদ" },
  79: { name: "আন-নাযি'আত", translation: "উৎপাটনকারী ফেরেশতা" },
  80: { name: "'আবাসা", translation: "ভ্রুকুটি করলেন" },
  81: { name: "আত-তাকভীর", translation: "অন্ধকারাচ্ছন্নকরণ" },
  82: { name: "আল-ইনফিতার", translation: "বিদীর্ণ হওয়া" },
  83: { name: "আল-মুতাফফিফীন", translation: "মাপে কম প্রদানকারী" },
  84: { name: "আল-ইনশিকাক", translation: "খণ্ড-বিখণ্ড হওয়া" },
  85: { name: "আল-বুরূজ", translation: "নক্ষত্রমণ্ডল" },
  86: { name: "আত-তারিক", translation: "রাতের আগমনকারী" },
  87: { name: "আল-আ'লা", translation: "সর্বোচ্চ মহান" },
  88: { name: "আল-গাশিয়াহ", translation: "আচ্ছন্নকারী মহাপ্রলয়" },
  89: { name: "আল-ফজর", translation: "ভোরবেলা" },
  90: { name: "আল-বালাদ", translation: "পবিত্র নগরী" },
  91: { name: "আশ-শামস", translation: "সূর্য" },
  92: { name: "আল-লায়ল", translation: "রাত" },
  93: { name: "আদ-দুহা", translation: "পূর্বাহ্নের সূর্যালোক" },
  94: { name: "আশ-শারহ", translation: "বক্ষ প্রশস্তকরণ" },
  95: { name: "আত-তীন", translation: "ডুমুর ফল" },
  96: { name: "আল-'আলাক", translation: "রক্তপিণ্ড" },
  97: { name: "আল-কদর", translation: "মহিমান্বিত রাত" },
  98: { name: "আল-বাইয়িনাহ", translation: "সুস্পষ্ট প্রমাণ" },
  99: { name: "আজ-যালযালাহ", translation: "মহাকম্পন" },
  100: { name: "আল-'আদিয়াত", translation: "অভিযানকারী অশ্ব" },
  101: { name: "আল-কারিয়াহ", translation: "মহা বিপদ" },
  102: { name: "আত-তাকাসুর", translation: "প্রাচুর্যের প্রতিযোগিতা" },
  103: { name: "আল-'আসর", translation: "সময়" },
  104: { name: "আল-হুমাযাহ", translation: "পরনিন্দাকারী" },
  105: { name: "আল-ফীল", translation: "হাতি" },
  106: { name: "কুরাইশ", translation: "কুরাইশ বংশ" },
  107: { name: "আল-মা'উন", translation: "নিত্যপ্রয়োজনীয় বস্তু" },
  108: { name: "আল-কাওসার", translation: "প্রচুর কল্যাণ" },
  109: { name: "আল-কাফিরুন", translation: "অবিশ্বাসী সম্প্রদায়" },
  110: { name: "আন-নাসর", translation: "সাহায্য ও বিজয়" },
  111: { name: "আল-মাসাদ", translation: "খেজুরের আঁশ" },
  112: { name: "আল-ইখলাস", translation: "একনিষ্ঠতা" },
  113: { name: "আল-ফালাক", translation: "প্রভাতকাল" },
  114: { name: "আন-নাস", translation: "মানবজাতি" },
};

export const BENGALI_RECITERS: Record<string, string> = {
  "Abdelbari Al-Toubayti": "আব্দেলবারি আল-তুবাইতি",
  "Abdelmoujib Benkirane": "আব্দেলমুজিব বেনকিরানে",
  "Abdul Aziz Al-Ahmad": "আব্দুল আজিজ আল-আহমদ",
  "Abdul Aziz az-Zahrani": "আব্দুল আজিজ আজ-জাহরানী",
  "Abdul Bari ath-Thubaity": "আব্দুল বারি আস-সুবাইতি",
  "Abdul Bari Mohammed": "আব্দুল বারী মুহাম্মদ",
  "Abdul Basit Abdus-Samad": "আব্দুল বাসিত আব্দুস সামাদ",
  "Abdul Basit Abdus-Samad (Mujawwad)": "আব্দুল বাসিত আব্দুস সামাদ (মুজাওয়াদ)",
  "Abdul Basit Abdus-Samad (Murattal)": "আব্দুল বাসিত আব্দুস সামাদ (মুরাত্তাল)",
  "Abdul Kareem al-Hazmi": "আব্দুল করীম আল-হাজমী",
  "Abdul Mohsen al-Harthy": "আব্দুল মুহসিন আল-হারসী",
  "Abdul Muhsin Al-Qasim": "আব্দুল মুহসিন আল-কাসিম",
  "Abdul Munim Abdul Mubdi": "আব্দুল মুনিম আব্দুল মুবদি",
  "Abdul Rahman Al-Sudais": "আব্দুর রহমান আস-সুদাইস",
  "Abdul Rahman Al-Sudais (Murattal)": "আব্দুর রহমান আস-সুদাইস (মুরাত্তাল)",
  "Abdul Rahman bin Abdul Razzaq Al Badr": "আব্দুর রহমান বিন আব্দুল রাজ্জাক আল বদর",
  "Abdul Wadood Haneef": "আব্দুল ওয়াদুদ হানিফ",
  "Abdulaziz Alturki": "আব্দুল আজিজ আল-তুর্কি",
  "Abdulaziz Az-Zahrani": "আব্দুল আজিজ আজ-জাহরানি",
  "Abdulbadi Ghailan": "আব্দুল বাদি গাইলান",
  "Abdulbari Mohammad": "আব্দুল বারি মোহাম্মদ",
  "Abdulbasit Abdulsamad": "আব্দুল বাসিত আব্দুল সামাদ",
  "Abdulbasit Abdusamad": "আব্দুল বাসিত আব্দুস সামাদ",
  "Abdulelah bin Aoun": "আব্দুল ইলাহ বিন আওন",
  "Abdulhadi Kanakeri": "আব্দুল হাদি কানাকেরি",
  "Abdulkareem Alhazmi": "আব্দুল করিম আল-হাজমি",
  "Abdullah Abdal": "আব্দুল্লাহ আবদাল",
  "Abdullah Al-Johany": "আব্দুল্লাহ আল-জুহানি",
  "Abdullah al-Juhany": "আব্দুল্লাহ আল-জুহানী",
  "Abdullah Al-Kandari": "আব্দুল্লাহ আল-কান্দারি",
  "Abdullah Al-Khalaf": "আব্দুল্লাহ আল-খালাফ",
  "Abdullah al-Khulaifi": "আব্দুল্লাহ আল-খুলাইফি",
  "Abdullah al-Matrood": "আব্দুল্লাহ আল-মাতরূদ",
  "Abdullah Al-Matrood": "আব্দুল্লাহ আল-ম্যাতরূদ",
  "Abdullah Al-Mattrod": "আব্দুল্লাহ আল-মাতরুদ",
  "Abdullah Al-Mousa": "আব্দুল্লাহ আল-মুসা",
  "Abdullah Albuajan": "আব্দুল্লাহ আল-বুয়াজান",
  "Abdullah Alqarafi": "আব্দুল্লাহ আল-কারাফি",
  "Abdullah Awad al-Juhani": "আব্দুল্লাহ আওয়াদ আল-জুহানী",
  "Abdullah Awad Al-Juhany": "আব্দুল্লাহ আওয়াদ আল-জুহানী",
  "Abdullah Basfer": "আব্দুল্লাহ বাসফার",
  "Abdullah Kamel": "আব্দুল্লাহ কামিল",
  "Abdullah Khayat": "আব্দুল্লাহ খাইয়্যাত",
  "Abdullah Khayyat": "আব্দুল্লাহ খাইয়াত",
  "Abdullah Qaulan": "আব্দুল্লাহ কাওলান",
  "Abdulmohsen Al-Qasim": "আব্দুল মোহসেন আল-কাসিম",
  "Abdulmohsin Al-Harthy": "আব্দুল মোহসিন আল-হারসি",
  "Abdulmohsin Al-Obaikan": "আব্দুল মোহসিন আল-ওবাইকান",
  "Abdulrahman Al-Majed": "আব্দুর রহমান আল-মাজেদ",
  "Abdulrahman Aloosi": "আব্দুর রহমান আল-উসি",
  "Abdulrahman Alshahhat": "আব্দুর রহমান আশ-শাহাত",
  "Abdulrahman Alsudaes": "আব্দুর রহমান আস-সুদাইস",
  "Abdulrasheed Soufi": "আব্দুর রশিদ সুফি",
  "Abdulwadood Haneef": "আব্দুল ওয়াদুদ হানিফ",
  "Abdulwali Al-Arkani": "আব্দুল ওয়ালি আল-আরকানি",
  "Abdur-Rasheed Sufi (Abul-Harith from al-Kisa'i)": "আব্দুর রশীদ সুফী (আবুল-হারিস - কিসাঈ)",
  "Abdur-Rasheed Sufi (ad-Doori from Abu Amr)": "আব্দুর রশীদ সুফী (আদ-দূরী - আবু আমর)",
  "Abdur-Rasheed Sufi (as-Soosi)": "আব্দুর রশীদ সুফী (আস-সূসী)",
  "Abdur-Rasheed Sufi (Shu'bah from Asim)": "আব্দুর রশীদ সুফী (শু'বাহ - আসিম)",
  "Abu Abdullah Munir at-Tounsi": "আবু আব্দুল্লাহ মুনির আত-তিউনিসি",
  "Abu Bakr adh-Dhabi": "আবু বকর আজ-জাবি",
  "Abu Bakr al-Shatri": "আবু বকর আশ-শাতরী",
  "Abu Bakr Al-Shatri": "আবু বকর আশ-শাতরী",
  "Addokali Mohammad Alalim": "আদ্দুকালি মোহাম্মদ আল-আলিম",
  "Adel Al-Khalbany": "আদেল আল-কালবানি",
  "Adel Ryyan": "আদেল রায়ান",
  "Adil al-Kalbani": "আদিল আল-কালবানি",
  "Ahmad Al Nufais": "আহমদ আন-নুফাইস",
  "Ahmad Al-Ajmy": "আহমদ আল-আজমি",
  "Ahmad Al-Hawashi": "আহমদ আল-হাওয়াশি",
  "Ahmad al-Hawashy": "আহমদ আল-হাওয়াশী",
  "Ahmad Deban": "আহমদ দিবান",
  "Ahmad Issa Al Maasaraawi": "আহমদ ঈসা আল-মাসারাওয়ী",
  "Ahmad Khader at-Tarabulsi": "আহমদ খাদের আত-তারাবুলসী",
  "Ahmad Nauina": "আহমদ নাইনা",
  "Ahmad Saber": "আহমদ সাবের",
  "Ahmad Shaheen": "আহমদ শাহিন",
  "Ahmad Sulaiman": "আহমদ সুলাইমান",
  "Ahmed al-Ajmi": "আহমদ আল-আজমী",
  "Ahmed al-Hammad": "আহমেদ আল-হাম্মাদ",
  "Ahmed al-Misbahi": "আহমেদ আল-মিসবাহি",
  "Ahmed Al-Swailem": "আহমেদ আস-সুওয়াইলেম",
  "Ahmed Al-trabulsi": "আহমেদ আল-তারাবুলসি",
  "Ahmed Amer": "আহমেদ আমের",
  "Ahmed Amir": "আহমদ আমির",
  "Ahmed ibn Ali al-Ajamy": "আহমদ ইবনে আলী আল-আজমী",
  "Ahmed Mohamed Salama": "আহমেদ মোহাম্মদ সালামা",
  "Ahmed Saber": "আহমদ সাবের",
  "Akram Al-Alaqmi": "আকরাম আল-আলাকমি",
  "Akram Alalaqmi": "আকরাম আল-আলাকমি",
  "al-Ashry Omran": "আল-আশরি ওমরান",
  "al-Fateh Muhammad Zubair": "আল-ফাতেহ মুহাম্মদ যুবাইর",
  "al-Husayni al-Azazi": "আল-হুসাইনি আল-আজাজি",
  "al-Husayni al-Azazi (with children)": "আল-হুসাইনী আল-আজাজী (শিশুদের সাথে)",
  "al-Obeikan": "আল-ওবাইকান",
  "Al-Qaria Yassen": "আল-কারি ইয়াসিন",
  "al-Zain Mohamed Ahmed": "আল-যাইন মুহাম্মদ আহমদ",
  "Alfateh Alzubair": "আল-ফাতেহ আজ-জুবায়ের",
  "Ali Abdur-Rahman al-Huthaify": "আলী আব্দুর রহমান আল-হুজাইফী",
  "Ali Abdur-Rahman al-Huthaify (Qaloon)": "আলী আব্দুর রহমান আল-হুজাইফী (কালুন)",
  "Ali al-Hudhaify": "আলী আল-হুজাইফী",
  "Ali Al-Huthaify": "আলী আল-হুজাইফী",
  "Ali Alhuthaifi": "আলি আল-হুজাইফি",
  "Ali Hajjaj Alsouasi": "আলি হাজ্জাজ আস-সুওয়াইসি",
  "Ali Hajjaj Souissi": "আলী হাজ্জাজ সুইসি",
  "Ali Jaber": "আলি জাবের",
  "Ali Jabir": "আলী জাবের",
  "Alijon Qori": "আলিজন ক্বারী",
  "Aloyoon Al-Koshi": "উয়ুন আল-কুশি",
  "Alzain Mohammad Ahmad": "আজ-জাইন মোহাম্মদ আহমদ",
  "Anas Alemadi": "আনাস আল-ইমাদি",
  "ar.oimaoqataris": "কাতারি ক্বারী পরিষদ",
  "Asim Al-Luhaidan": "আসিম আল-লুহাইদান",
  "Ayman Swed": "আইমান সুওয়াইদ",
  "Aziz Alili": "আজিজ আলিলি",
  "Bader Alturki": "বদর আল-তুর্কি",
  "Bandar Baleela": "বান্দার বালীলাহ",
  "Bandar Balilah": "বান্দার বালিলা",
  "Bassel Abdul-Rahman ar-Raoui": "বাসেল আব্দুর রহমান আল-রাওয়ী",
  "Benkirane": "বেনকিরানে",
  "Darwish Faraj Darwish al-Attar": "দারউইশ ফারাজ দারউইশ আল-আত্তার",
  "Dawood Hamza": "দাউদ হামজা",
  "Emad al-Mansary": "ইমাদ আল-মানসারি",
  "Emad Hafez": "ইমাদ হাফেজ",
  "Ezzat Sabri": "ইজ্জত সাবরি",
  "Faisal Al-Hajry": "ফয়সাল আল-হাজরি",
  "Fares Abbad": "ফারেস আব্বাদ",
  "Fouad al-Khamiri": "ফুয়াদ আল-খামিরী",
  "Fouad Alkhamery": "ফুয়াদ আল-খামেরি",
  "Haitham Aldukhain": "হাইসাম আদ-দুখাইন",
  "Hamad Sinan": "হামাদ সিনান",
  "Hamdy al-Sayed Tolba Saad": "হামদি আস-সাইয়্যেদ তলবা সাদ",
  "Hani ar-Rifai": "হানি আর-রিফাঈ",
  "Hani Ar-Rifai": "হানি আর-রিফাঈ",
  "Hani Arrifai": "হানি আর-রিফাই",
  "Hasan Hashem": "হাসান হাশেম",
  "Hasan Saleh": "হাসান সালেহ",
  "Hashim Abu Dalal": "হাশিম আবু দালাল",
  "Hassan Aldaghriri": "হাসান আদ-দাগরিরি",
  "Hassan Saleh": "হাসান সালেহ",
  "Hatem Fareed Alwaer": "হাতেম ফরিদ আল-ওয়ায়ের",
  "Hatem Farid": "হাতেম ফরিদ",
  "Hazza Al-Balushi": "হাজ্জা আল-বালুশী",
  "Ibrahim ad-Dossari": "ইব্রাহীম আদ-দাওসারী",
  "Ibrahim Al-Akdar": "ইব্রাহিম আল-আখদার",
  "Ibrahim al-Akhdar": "ইব্রাহিম আল-আখদার",
  "Ibrahim Al-Asiri": "ইব্রাহিম আল-আসিরি",
  "Ibrahim al-Jormy": "ইব্রাহীম আল-জারমী",
  "Ibrahim Aldosari": "ইব্রাহিম আল-দোসারি",
  "Ibrahim Aljormy": "ইব্রাহিম আল-জুরমি",
  "Ibrahim Kshidan": "ইব্রাহিম কাশিদান",
  "Idrees Abkr": "ইদ্রিস আবকার",
  "Idris Abkar": "ইদ্রিস আবকার",
  "Ilhan Tok": "ইলহান তোক",
  "Imad Zuhair Hafez": "ইমাদ জুহাইর হাফেজ",
  "Islam Sobhi": "ইসলাম সোবহী",
  "Issa Omar Sanankoua": "ঈসা ওমর সানানকুয়া",
  "Jamaan al-Osaimi": "জামান আল-উসাইমী",
  "Jamaan Alosaimi": "জামান আল-উসাইমি",
  "Jamal Shaker Abdullah": "জামাল শাকের আব্দুল্লাহ",
  "Jazza al-Swaileh": "জাজ্জা আস-সুওয়াইলিহ",
  "Junaid Adam Abdullah": "জুনায়েদ আদম আব্দুল্লাহ",
  "Kamel": "কামেল",
  "Khaled al-Qahtani": "খালেদ আল-কাহতানী",
  "Khaled Al-Qahtani": "খালেদ আল-কাহতানি",
  "Khaled Barakat": "খালেদ বারাকাত",
  "Khalid Abdul-Kafi": "খালিদ আব্দুল-কাফী",
  "Khalid Abdulkafi": "খালিদ আব্দুল কাফি",
  "Khalid al-Jalil": "খালিদ আল-জালীল",
  "Khalid Al-Jalil": "খালিদ আল-জালীল",
  "Khalid Al-Jileel": "খালিদ আল-জলিল",
  "Khalid al-Mohanna": "খালিদ আল-মুহান্না",
  "Khalid Almohana": "খালিদ আল-মুহান্না",
  "Khalid Alziyadi": "খালিদ আজ-জিয়াদি",
  "Khalid Mohammadi": "খালিদ মোহাম্মাদি",
  "Khalifa Al-Tunaiji": "খলিফা আল-তুনাইজি",
  "Khalifa Altunaiji": "খলিফা আল-তুনাইজি",
  "Khalifa at-Tunaiji": "খলিফা আল-তুনাইজি",
  "Laayoun el-Kouchi": "লাআউন আল-কুশি",
  "Maher Al Meaqli": "মাহের আল-মুআইকলি",
  "Maher al-Mu`aiqly": "মাহের আল-মুআইকলী",
  "Maher Al-Muaiqly": "মাহের আল-মুআইকলী",
  "Maher Shakhashero": "মাহের শাখাশিরো",
  "Maher Shakhashiro": "মাহের শাখাশিরু",
  "Mahmood Al rifai": "মাহমুদ আল-রিফাই",
  "Mahmood al-Rifai": "মাহমুদ আর-রিফাঈ",
  "Mahmood AlSheimy": "মাহমুদ আশ-শাইমি",
  "Mahmoud Abdul Hakam": "মাহমুদ আব্দুল হাকাম",
  "Mahmoud Ali  Albanna": "মাহমুদ আলি আল-বান্না",
  "Mahmoud Ali al-Banna": "মাহমুদ আলী আল-বান্না",
  "Mahmoud el-Sheimy": "মাহমুদ আশ-শিমী",
  "Mahmoud Harfoush": "মাহমুদ হারফুশ",
  "Mahmoud Khaleel Al-Husary": "মাহমুদ খলিল আল-হুসারী",
  "Mahmoud Khaleel Al-Husary (Mu'allim)": "মাহমুদ খলিল আল-হুসারী (মুয়াল্লিম)",
  "Mahmoud Khaleel Al-Husary (Mujawwad)": "মাহমুদ খলিল আল-হুসারী (মুজাওয়াদ)",
  "Mahmoud Khalil Al-Husary": "মাহমুদ খলিল আল-হুসারী",
  "Mahmoud Khalil Al-Hussary": "মাহমুদ খলিল আল-হুসারি",
  "Mahmoud Saad Darouich": "মাহমুদ সাদ দারউইশ",
  "Mahmoud Sayed el-Tayeb": "মাহমুদ সাইয়্যেদ আত-তায়িব",
  "Majed Al-Zamil": "মাজেদ আল-জামিল",
  "Mal-Allah Abdulrhman Aljaber": "মাল-আল্লাহ আব্দুর রহমান আল-জাবের",
  "Mansour Al-Salemi": "মনসুর আস-সালেমি",
  "Marwan Alakri": "মারওয়ান আল-আকরি",
  "Mishari Rashid al-`Afasy": "মিশারী রাশিদ আল-আফাসী",
  "Mishari Rashid al-`Afasy (Mujawwad)": "মিশারী রাশিদ আল-আফাসী (মুজাওয়াদ)",
  "Mishary Alafasi": "মিশারি আল-আফাসি",
  "Mishary Alafasy": "মিশারি আল-আফাসি",
  "Mishary Rashid Alafasy": "মিশারী রাশিদ আল-আফাসী",
  "Moeedh al-Harthi": "মুঈদ আল-হারসী",
  "Moeedh Alharthi": "মুয়িজ আল-হারসি",
  "Mohamed Abdel-Aziz": "মোহাম্মদ আব্দুল আজিজ",
  "Mohamed Abdel-Hakim Saad al-Abdullah": "মুহাম্মদ আব্দুল হাকিম সা'দ আল-আব্দুল্লাহ",
  "Mohamed al-Jabery al-Heyani": "মোহাম্মদ আল-জাবেরী আল-হায়ানি",
  "Mohamed al-Mohisni": "মুহাম্মদ আল-মুহাইসনী",
  "Mohamed at-Tablawi": "মুহাম্মদ আত-তাবলাওয়ী",
  "Mohamed el-Kantaoui": "মোহাম্মদ আল-কান্তাওয়ী",
  "Mohamed Hassan": "মোহাম্মদ হাসান",
  "Mohamed Maabad": "মোহাম্মদ মা’বাদ",
  "Mohamed Osman Khan": "মুহাম্মদ উসমান খান",
  "Mohamed Shaaban Abu Qarn": "মোহাম্মদ শাবান আবু কারন",
  "Mohamed Siddiq El-Minshawi": "মুহাম্মদ সিদ্দিক আল-মিনশাবী",
  "Mohammad Abdullkarem": "মোহাম্মদ আব্দুল করিম",
  "Mohammad Al-Abdullah": "মোহাম্মদ আল-আব্দুল্লাহ",
  "Mohammad Al-Tablaway": "মোহাম্মদ আত-তাবলাওয়ী",
  "Mohammad Albukheet": "মোহাম্মদ আল-বুখিত",
  "Mohammad Ismaeel al-Muqaddim": "মোহাম্মদ ইসমাইল আল-মুকাদ্দিম",
  "Mohammad Khalil Al-Qari": "মোহাম্মদ খলিল আল-ক্বারী",
  "Mohammad Rachad al-Shareef": "মুহাম্মদ রাশাদ আশ-শারীফ",
  "Mohammad Rashad Alshareef": "মোহাম্মদ রাশাদ আশ-শরিফ",
  "Mohammad Saayed": "মোহাম্মদ সাইয়্যেদ",
  "Mohammad Saleh Alim Shah": "মোহাম্মদ সালেহ আলিম শাহ",
  "Mohammed Al-Amin Qeniwa": "মোহাম্মদ আল-আমিন ক্বেনাওয়া",
  "Mohammed Al-Lohaidan": "মোহাম্মদ আল-লুহাইদান",
  "Mohammed Al-Muhasny": "মোহাম্মদ আল-মুহাইসনি",
  "Mohammed Al-Zubaidi": "মোহাম্মদ আজ-জুবাইদি",
  "Mohammed Ayyub": "মোহাম্মদ আইয়ুব",
  "Mohammed bin Saleh Abu Zaid": "মোহাম্মদ বিন সালেহ আবু জায়েদ",
  "Mohammed Jibreel": "মোহাম্মদ জিবরিল",
  "Mohammed Osman Khan": "মোহাম্মদ উসমান খান",
  "Mohammed Siddiq Al-Minshawi": "মোহাম্মদ সিদ্দিক আল-মিনশাবি",
  "Mousa Bilal": "মুসা বিলাল",
  "Muftah al-Saltany": "মুফতাহ আস-সালতানী",
  "Muftah Alsaltany": "মুফতাহ আস-সালতানি",
  "Muhammad Abdul-Kareem": "মুহাম্মদ আব্দুল করিম",
  "Muhammad Abu Sneina": "মুহাম্মদ আবু সুনাইনা",
  "Muhammad Al Faqih": "মুহাম্মদ আল-ফকিহ",
  "Muhammad al-Aalim ad-Dokali": "মুহাম্মদ আল-আলিম আদ-দোকালি",
  "Muhammad al-Luhaidan": "মুহাম্মদ আল-লুহাইদান",
  "Muhammad al-Mehysni": "মুহাম্মদ আল-মুহাইসনী",
  "Muhammad Anwar Shahat": "মুহাম্মদ আনোয়ার শাহাত",
  "Muhammad as-Subayyil": "মুহাম্মদ আস-সুবায়িল",
  "Muhammad Ayyub": "মুহাম্মদ আইয়ুব",
  "Muhammad Burhaji": "মুহাম্মদ বুরহাজি",
  "Muhammad Saleh Alim Shah": "মুহাম্মদ সালেহ আলিম শাহ",
  "Muhammad Siddiq al-Minshawi": "মুহাম্মদ সিদ্দিক আল-মিনশাবী",
  "Muhammad Siddiq al-Minshawi (Mujawwad)": "মুহাম্মদ সিদ্দিক আল-মিনশাবী (মুজাওয়াদ)",
  "Muhammad Sulaiman Patel": "মুহাম্মদ সুলাইমান প্যাটেল",
  "Mukhtar Al-Haj": "মুখতার আল-হজ",
  "Musa Bilal": "মুসা বিলাল",
  "Mustafa Al-Lahoni": "মুস্তফা আল-লাহুনি",
  "Mustafa al-Lahouni": "মুস্তফা আল-লাহুনী",
  "Mustafa Ismail": "মুস্তফা ইসমাইল",
  "Mustafa Raad al-Azzawi": "মুস্তফা রাদ আল-আজজাবি",
  "Mustafa raad Alazawy": "মুস্তফা রাদ আল-আজজাবি",
  "Mustapha Gharbi": "মুস্তফা আল-গারবি",
  "Nabil Al Rifay": "নাবিল আর-রিফাই",
  "Nabil ar-Rifai": "নাবিল আর-রিফাঈ",
  "Nabil Ar-Rifai": "নাবিল আর-রিফাঈ",
  "Nasser al-Qatami": "নাসের আল-কাতামী",
  "Nasser Al-Qatami": "নাসের আল-কাতামী",
  "Nasser Almajed": "নাসের আল-মাজেদ",
  "Nasser Alosfor": "নাসের আল-উসফুর",
  "Nasser Alqatami": "নাসের আল-কাতামি",
  "Nathier Almalki": "নাজির আল-মালকি",
  "Neamah al-Hassan": "নি'মাহ আল-হাসান",
  "Neamah Al-Hassan": "নে’মাহ আল-হাসান",
  "Noreen Mohammad Siddiq": "নুরিন মোহাম্মদ সিদ্দিক",
  "Okasha Kameny": "ওকাশা কামেনি",
  "Omar Al Darweez": "ওমর আল-দারউইজ",
  "Omar al-Kazabri": "ওমর আল-কাজাবরি",
  "Omar Al-Qazabri": "ওমর আল-কাজাবরি",
  "Osama bin Ali al-Ghanim": "ওসামা বিন আলি আল-গানিম",
  "Peshawa Qadr Al-Kurdi": "পেশাওয়া কাদির আল-কুর্দি",
  "Raad Al Kurdi": "রাদ আল-কুর্দি",
  "Raad Mohammad Al-Kurdi": "রা'দ মুহাম্মদ আল-কুরদী",
  "Rachid Belalia": "রাশিদ বেলালিয়া",
  "Rachid Belalya": "রশিদ বেলালায়া",
  "Rami Aldeais": "রামি আদ-দায়িস",
  "Sa'ud al-Shuraym": "সাউদ আশ-শুরাইম",
  "Sa`d al-Ghamdi": "সা'দ আল-গামদী",
  "Saad Al-Ghamdi": "সাদ আল-গামদি",
  "Saad Almqren": "সাদ আল-মুকরিন",
  "Saber Abdul-Hakam": "সাবের আব্দুল হাকাম",
  "Saber Abdulhakm": "সাবের আব্দুল হাকাম",
  "Sadaqat Ali": "সাদাকাত আলি",
  "Sahl Yasin": "সাহল ইয়াসিন",
  "Sahl Yassin": "সাহল ইয়াসিন",
  "Said ash-Shaalan": "সাঈদ আশ-শালান",
  "Salah al-Budair": "সালাহ আল-বুদাইর",
  "Salah Al-Budair": "সালাহ আল-বুদাইর",
  "Salah al-Hashem": "সালাহ আল-হাশেম",
  "Salah Albudair": "সালাহ আল-বুদাইর",
  "Salah Alhashim": "সালাহ আল-হাশিম",
  "Salah Ba-Othman": "সালাহ বা-উসমান",
  "Salah Bukhatir": "সালাহ বুখাতির",
  "Saleh Al-Habdan": "সালেহ আল-হাবদান",
  "Saleh Alquraishi": "সালেহ আল-কুরাইশি",
  "Saleh Alsahood": "সালেহ আস-সাহুদ",
  "Saleh Alshamrani": "সালেহ আশ-শামরানি",
  "Salman Alsadeiq": "সালমান আস-সাদিক",
  "Samir Belaachya": "সমির বেলাশিয়া",
  "Saud Al-Shuraim": "সাউদ আশ-শুরাইম",
  "Saud ash-Shuraim": "সাউদ আশ-শুরাইম",
  "Sayed Ahmad Hashemi": "সাইয়্যেদ আহমদ হাশেমি",
  "Sayed Ramadan": "সায়্যেদ রমাদান",
  "Sayeed Ramadan": "সাইয়্যেদ রমজান",
  "Shahriar Parhizgar": "শাহরিয়ার পারহিজগার",
  "Shaik Abu Bakr Al Shatri": "শায়খ আবু বকর আশ-শাতরি",
  "Shirazad Taher": "শিরাজাদ তাহের",
  "Slaah Bukhatir": "সালাহ বুখাতির",
  "Tamer Islam": "তামের ইসলাম",
  "Tareq Abdul-Gani Daawob": "তারেক আব্দুল গনী দাওব",
  "Tareq Abdulgani daawob": "তারিক আব্দুল গনি দাওব",
  "Tawfeeq as-Sayegh": "তাওফিক আস-সায়েগ",
  "Tawfeeq As-Sayegh": "তৌফিক আস-সায়িগ",
  "Turki Ebeid al-Marri": "তুর্কি উবাইদ আল-মাররি",
  "Wadee Al-Yamani": "ওয়াদিহ আল-ইয়ামানী",
  "Wadeea Al-Yamani": "ওয়াদিয়া আল-ইয়ামানি",
  "Wael ad-Desouky": "ওয়ায়েল আদ-দেসুকি",
  "Wael Radwan Qureshi": "ওয়ায়েল রাদওয়ান কুরাইশি",
  "Waleed Al-Dulaimi": "ওয়ালিদ আল-দুলাইমি",
  "Waleed Alnaehi": "ওয়ালিদ আন-নাহি",
  "Waleed an-Naehi": "ওয়ালিদ আন-নায়হী",
  "Waleed Idrees al-Maneese": "ওয়ালিদ ইদ্রিস আল-মানিসি",
  "Waleed Samir Ali Abdul-Majid Sorour": "ওয়ালিদ সামির আলি আব্দুল মজিদ সুরুর",
  "Walid ash-Shatti": "ওয়ালিদ আশ-শাত্তি",
  "Walid Fathi Bashta": "ওয়ালিদ ফাতহি বাশতা",
  "Yahya Hawwa": "ইয়াহিয়া হাওয়া",
  "Yassen al-Jazairi": "ইয়াসিন আল-জাজাইরি",
  "Yasser ad-Dossari": "ইয়াসির আদ-দাওসারী",
  "Yasser al-Dosari": "ইয়াসির আদ-দাওসারী",
  "Yasser Al-Dosari": "ইয়াসির আদ-দোসারি",
  "Yasser al-Mazroyee": "ইয়াসির আল-মাজরুঈ",
  "Yasser Al-Mazroyee": "ইয়াসির আল-মাজরুই",
  "Yasser Al-Qurashi": "ইয়াসির আল-কুরাশি",
  "Yasser Qureshi": "ইয়াসির কুরেশী",
  "Yasser Salama": "ইয়াসির সালামা",
  "Yasser Salamah": "ইয়াসির সালামা",
  "Yasser Sarhan el-Deeb": "ইয়াসির সারহান আদ-দিব",
  "Yousef Al-Showaie": "ইউসুফ আশ-শোয়াই",
  "Yousef Alshoaey": "ইউসুফ আশ-শুআই",
  "Yousef Bin Noah Ahmad": "ইউসুফ বিন নূহ আহমদ",
  "Yousuf ash-Shoaey": "ইউসুফ আশ-শুয়াই",
  "Yousuf bin Noah Ahmad": "ইউসুফ বিন নূহ আহমদ",
  "Yusuf ALaidroos": "ইউসুফ আল-আইদ্রুস",
  "Zaki Daghistani": "জাকি দাগিস্তানি",
};


const BN_DIGITS = ["০", "১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯"];

export function toBengaliDigits(num: number | string): string {
  return String(num).replace(/[0-9]/g, (d) => BN_DIGITS[Number(d)] ?? d);
}

export function fromBengaliDigits(str: string): string {
  return str.replace(/[০-৯]/g, (ch) => String(BN_DIGITS.indexOf(ch)));
}

export function getLocalizedSurahName(surah: Surah | undefined, locale?: string): string {
  if (!surah) return "";
  if (locale === "bn") {
    return BENGALI_SURAHS[surah.id]?.name ?? surah.name;
  }
  return surah.name;
}

export function getLocalizedSurahTranslation(surah: Surah | undefined, locale?: string): string {
  if (!surah) return "";
  if (locale === "bn") {
    return BENGALI_SURAHS[surah.id]?.translation ?? surah.translation;
  }
  return surah.translation;
}

const LOWER_BENGALI_RECITERS = new Map<string, string>();
for (const [key, val] of Object.entries(BENGALI_RECITERS)) {
  LOWER_BENGALI_RECITERS.set(key.toLowerCase().trim(), val);
}

export function getLocalizedReciterName(name: string, locale?: string): string {
  if (locale !== "bn") return name;
  const trimmed = name.trim();
  const direct = BENGALI_RECITERS[trimmed];
  if (direct) return direct;

  const lower = trimmed.toLowerCase();
  const fromLower = LOWER_BENGALI_RECITERS.get(lower);
  if (fromLower) return fromLower;

  const normKey = lower.replace(/[^a-z0-9]/g, " ").replace(/\s+/g, " ");
  for (const [k, v] of LOWER_BENGALI_RECITERS.entries()) {
    if (k.replace(/[^a-z0-9]/g, " ").replace(/\s+/g, " ") === normKey) {
      return v;
    }
  }

  const words = normKey.split(" ").filter((w) => w.length > 2 && w !== "al" && w !== "bin" && w !== "abu");
  if (words.length > 0) {
    for (const [k, v] of LOWER_BENGALI_RECITERS.entries()) {
      const kWords = k.replace(/[^a-z0-9]/g, " ").toLowerCase();
      if (words.every((w) => kWords.includes(w))) {
        return v;
      }
    }
  }

  return name;
}

export const BENGALI_MOSHAFS: Record<string, string> = {
  // Styles
  Murattal: "মুরাত্তাল",
  Mujawwad: "মুজাওয়াদ",
  Muallim: "মুয়াল্লিম (শিক্ষণ)",
  "Featured Recitation": "বিশিষ্ট তিলাওয়াত",
  "Al-Mus'haf Al-Murattal": "মুরাত্তাল তিলাওয়াত",
  "Al-Mus'haf Al-Mujawwad": "মুজাওয়াদ তিলাওয়াত",
  "Al-Mus'haf Al-Moallim": "মুয়াল্লিম তিলাওয়াত",
  "Almusshaf Al Mo'lim": "মুয়াল্লিম (শিক্ষণ তিলাওয়াত)",
  "Almusshaf Al Mojawwad": "মুজাওয়াদ তিলাওয়াত",
  "with children": "শিশুদের সাথে (মুয়াল্লিম)",
  "With children": "শিশুদের সাথে (মুয়াল্লিম)",

  // Hafs
  Hafs: "হাফস",
  "Hafs A'n Assem": "হাফস আন আসিম",
  "Hafs an Asim": "হাফস আন আসিম",
  "Hafs A'n Assem, Murattal": "হাফস আন আসিম (মুরাত্তাল)",
  "Hafs A'n Assem, Featured Recitation": "হাফস আন আসিম (বিশিষ্ট তিলাওয়াত)",
  "Hafs A'n Assem, Recorded in 1387 AH (1967 CE)": "হাফস আন আসিম, ১৩৮৭ হি. (১৯৬৭ খ্রি.)",

  // Warsh
  Warsh: "ওয়ারশ",
  "Warsh A'n Nafi'": "ওয়ারশ আন নাফি",
  "Warsh A'n Nafi', Murattal": "ওয়ারশ আন নাফি (মুরাত্তাল)",
  "Warsh A'n Nafi' Men Tariq Alazraq, Murattal": "ওয়ারশ আন নাফি (আল-আজরাক), মুরাত্তাল",
  "Warsh A'n Nafi' Men  Tariq Abi Baker Alasbahani, Murattal": "ওয়ারশ আন নাফি (আসবাহানী), মুরাত্তাল",
  "Warsh A'n Nafi' Men Tariq Abi Baker Alasbahani, Murattal": "ওয়ারশ আন নাফি (আসবাহানী), মুরাত্তাল",

  // Qalun
  Qalon: "কালূন",
  Qaloon: "কালূন",
  "Qalon A'n Nafi'": "কালূন আন নাফি",
  "Qaloon A'n Nafi'": "কালূন আন নাফি",
  "Qalon A'n Nafi', Murattal": "কালূন আন নাফি (মুরাত্তাল)",
  "Qalon A'n Nafi' Men Tariq Abi Nasheet, Murattal": "কালূন আন নাফি (আবী নাশীত), মুরাত্তাল",

  // As-Soosi
  "as-Soosi": "আস-সূসী",
  "As-Soosi": "আস-সূসী",
  "Assosi A'n Abi Amr": "আস-সূসী আন আবী আমর",
  "Assosi A'n Abi Amr, Murattal": "আস-সূসী আন আবী আমর (মুরাত্তাল)",

  // Ad-Doori
  "ad-Doori from Abu Amr": "আদ-দূরী আন আবী আমর",
  "Ad-Doori from Abu Amr": "আদ-দূরী আন আবী আমর",
  "Aldori A'n Abi Amr": "আদ-দূরী আন আবী আমর",
  "Aldori A'n Abi Amr, Murattal": "আদ-দূরী আন আবী আমর (মুরাত্তাল)",
  "AlDorai A'n Al-Kisa'ai, Murattal": "আদ-দূরী আন আল-কিসাঈ (মুরাত্তাল)",
  "AlDorai A'n Al-Kisa'ai": "আদ-দূরী আন আল-কিসাঈ",

  // Abul-Harith
  "Abul-Harith from al-Kisa'i": "আবুল-হারিস আন আল-কিসাঈ",

  // Shu'bah
  "Shu'bah from Asim": "শুবাহ আন আসিম",
  "Sho'bah A'n Asim, Murattal": "শুবাহ আন আসিম (মুরাত্তাল)",
  "Sho'bah A'n Asim": "শুবাহ আন আসিম",
  "Shu'bah": "শুবাহ",

  // Khalaf
  "Khalaf A'n Hamzah, Murattal": "খালাফ আন হামযাহ (মুরাত্তাল)",
  "Khalaf A'n Hamzah": "খালাফ আন হামযাহ",
  Khalaf: "খালাফ",

  // Ibn Katheer
  "Albizi A'n Ibn Katheer, Murattal": "আল-বাযযী আন ইবনে কাছীর (মুরাত্তাল)",
  "Albizi A'n Ibn Katheer": "আল-বাযযী আন ইবনে কাছীর",
  "Qunbol A'n Ibn Katheer, Murattal": "কুনবুল আন ইবনে কাছীর (মুরাত্তাল)",
  "Qunbol A'n Ibn Katheer": "কুনবুল আন ইবনে কাছীর",
  "Albizi and Qunbol A'n Ibn Katheer, Murattal": "বাযযী ও কুনবুল আন ইবনে কাছীর (মুরাত্তাল)",

  // Ibn Amer
  "Hesham A'n Abi A'mer, Murattal": "হিশাম আন আবী আমির (মুরাত্তাল)",
  "Hesham A'n Abi A'mer": "হিশাম আন আবী আমির",
  "Ibn Thakwan A'n Ibn Amer, Murattal": "ইবনে যাকওয়ান আন ইবনে আমির (মুরাত্তাল)",
  "Ibn Thakwan A'n Ibn Amer": "ইবনে যাকওয়ান আন ইবনে আমির",

  // Abu Ja'far
  "Ibn Jammaz A'n Abi Ja'far, Murattal": "ইবনে জাম্মায আন আবী জাফর (মুরাত্তাল)",
  "Ibn Jammaz A'n Abi Ja'far": "ইবনে জাম্মায আন আবী জাফর",

  // Ya'qub Al-Hadrami
  "Rowis and Rawh A'n Yakoob Al Hadrami, Murattal": "রুওয়ায়স ও রাওহ আন ইয়াকূব আল-হাযরামী (মুরাত্তাল)",
  "Rowis and Rawh A'n Yakoob Al Hadrami": "রুওয়ায়স ও রাওহ আন ইয়াকূব আল-হাযরামী",
};

const LOWER_BENGALI_MOSHAFS = new Map<string, string>();
for (const [k, v] of Object.entries(BENGALI_MOSHAFS)) {
  LOWER_BENGALI_MOSHAFS.set(k.toLowerCase().trim(), v);
}

export function getLocalizedMoshafName(name: string, locale?: string): string {
  if (locale !== "bn") return name;
  const trimmed = name.trim();
  const direct = BENGALI_MOSHAFS[trimmed];
  if (direct) return direct;

  const lower = trimmed.toLowerCase();
  const fromLower = LOWER_BENGALI_MOSHAFS.get(lower);
  if (fromLower) return fromLower;

  const norm = lower.replace(/[^a-z0-9]/g, " ").replace(/\s+/g, " ").trim();
  for (const [k, v] of LOWER_BENGALI_MOSHAFS.entries()) {
    const kNorm = k.replace(/[^a-z0-9]/g, " ").replace(/\s+/g, " ").trim();
    if (kNorm === norm) return v;
  }

  // Component fallback if split by comma
  if (trimmed.includes(",")) {
    const parts = trimmed.split(",").map((p) => p.trim());
    const localizedParts = parts.map((p) => getLocalizedMoshafName(p, locale));
    if (localizedParts.some((p, i) => p !== parts[i])) {
      return localizedParts.join(", ");
    }
  }

  return name;
}
